#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import QRCode from 'qrcode';

const url = (process.env.NEXT_NGROK_WEB_APP_URL ?? '').trim();
const qrDataUri = url ? await QRCode.toDataURL(url, { margin: 1, width: 480 }) : '';

const outPath = path.join(import.meta.dirname, '..', 'lib', 'uploadQr.ts');
const contents = `// Generated by scripts/generate-qr.mjs from NEXT_NGROK_WEB_APP_URL before dev/build/typecheck. Do not edit by hand.
export const uploadUrl = ${JSON.stringify(url)};
export const uploadQrDataUri = ${JSON.stringify(qrDataUri)};
`;

await mkdir(path.dirname(outPath), { recursive: true });
await writeFile(outPath, contents);

console.log(url
  ? `Generated upload QR code for ${url}`
  : 'NEXT_NGROK_WEB_APP_URL is not set; DemoThirteen will render its "awaiting upload link" placeholder.');
